spring.application.name=EcommerceAPI

# JWT configuration de connexion
# jwt Secret key
jwt.secret=mysecretkeymysecretkeymysecretkey12


# H2 Database
#  http://localhost:8082/h2-console .

# Activer la console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
 
# nom de la base en memoire
# mem c'est pour signifier que la base est en memoire
spring.datasource.url=jdbc:h2:file:./data/Ecommercedb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
# Le dialect H2 est détecté automatiquement, pas besoin de le spécifier
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Désactive l'avertissement open-in-view (pas utile en REST API)
spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update

# Exécuter data.sql au démarrage (src/main/resources/data.sql)
spring.sql.init.mode=always
# S'assurer que JPA crée le schéma AVANT que data.sql soit injecté
spring.jpa.defer-datasource-initialization=true

# resoud le probleme de lazy loading dans les controllers 
spring.jpa.open-in-view=true